[2022-12-07T10:45:17.630+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T10:45:10.785221+00:00 [queued]>
[2022-12-07T10:45:17.647+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T10:45:10.785221+00:00 [queued]>
[2022-12-07T10:45:17.647+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T10:45:17.648+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T10:45:17.649+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T10:45:17.670+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): pull_data> on 2022-12-07 10:45:10.785221+00:00
[2022-12-07T10:45:17.676+0000] {standard_task_runner.py:55} INFO - Started process 1375 to run task
[2022-12-07T10:45:17.680+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'pull_data', 'manual__2022-12-07T10:45:10.785221+00:00', '--job-id', '1697', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpl_va0sxn']
[2022-12-07T10:45:17.681+0000] {standard_task_runner.py:83} INFO - Job 1697: Subtask pull_data
[2022-12-07T10:45:17.781+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.pull_data manual__2022-12-07T10:45:10.785221+00:00 [running]> on host ede3719a0239
[2022-12-07T10:45:17.894+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T10:45:10.785221+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T10:45:10.785221+00:00
[2022-12-07T10:45:17.920+0000] {logging_mixin.py:137} INFO - connection to server at "database" (172.21.0.3), port 5432 failed: FATAL:  password authentication failed for user "***_user"
[2022-12-07T10:45:17.922+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-07T10:45:17.944+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=pull_data, execution_date=20221207T104510, start_date=20221207T104517, end_date=20221207T104517
[2022-12-07T10:45:18.013+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-07T10:45:18.037+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
