[2022-12-06T22:59:28.642+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-06T22:59:23.151342+00:00 [queued]>
[2022-12-06T22:59:28.656+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-06T22:59:23.151342+00:00 [queued]>
[2022-12-06T22:59:28.657+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T22:59:28.657+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-06T22:59:28.658+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T22:59:28.677+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): pull_data> on 2022-12-06 22:59:23.151342+00:00
[2022-12-06T22:59:28.682+0000] {standard_task_runner.py:55} INFO - Started process 4521 to run task
[2022-12-06T22:59:28.685+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'pull_data', 'manual__2022-12-06T22:59:23.151342+00:00', '--job-id', '1329', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9jbsnk6u']
[2022-12-06T22:59:28.686+0000] {standard_task_runner.py:83} INFO - Job 1329: Subtask pull_data
[2022-12-06T22:59:28.765+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.pull_data manual__2022-12-06T22:59:23.151342+00:00 [running]> on host 505aa50095aa
[2022-12-06T22:59:28.859+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T22:59:23.151342+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T22:59:23.151342+00:00
[2022-12-06T22:59:28.871+0000] {logging_mixin.py:137} INFO - [['2022-12-06', 'USD', 'EUR', 0.95530319], ['2022-12-06', 'USD', 'RUB', 63.38344107], ['2022-12-06', 'EUR', 'RUB', 66.34903103]]
[2022-12-06T22:59:28.884+0000] {logging_mixin.py:137} INFO - Failed to insert into PostgreSQL
[2022-12-06T22:59:28.885+0000] {logging_mixin.py:137} INFO - relation "pairs" does not exist
LINE 1: INSERT INTO pairs VALUES('v')
                    ^
[2022-12-06T22:59:28.886+0000] {logging_mixin.py:137} INFO - CSSS
[2022-12-06T22:59:28.887+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-06T22:59:28.903+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=pull_data, execution_date=20221206T225923, start_date=20221206T225928, end_date=20221206T225928
[2022-12-06T22:59:28.937+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-06T22:59:28.958+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
