[2022-12-06T22:07:03.781+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-06T22:06:59.069470+00:00 [queued]>
[2022-12-06T22:07:03.796+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-06T22:06:59.069470+00:00 [queued]>
[2022-12-06T22:07:03.797+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T22:07:03.798+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-06T22:07:03.799+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T22:07:03.818+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): pull_data> on 2022-12-06 22:06:59.069470+00:00
[2022-12-06T22:07:03.823+0000] {standard_task_runner.py:55} INFO - Started process 1834 to run task
[2022-12-06T22:07:03.826+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'pull_data', 'manual__2022-12-06T22:06:59.069470+00:00', '--job-id', '1184', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpa2zb96ph']
[2022-12-06T22:07:03.827+0000] {standard_task_runner.py:83} INFO - Job 1184: Subtask pull_data
[2022-12-06T22:07:03.909+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.pull_data manual__2022-12-06T22:06:59.069470+00:00 [running]> on host 505aa50095aa
[2022-12-06T22:07:04.005+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T22:06:59.069470+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T22:06:59.069470+00:00
[2022-12-06T22:07:04.018+0000] {logging_mixin.py:137} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2022-12-06T22:07:04.018+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-06T22:07:04.034+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=pull_data, execution_date=20221206T220659, start_date=20221206T220703, end_date=20221206T220704
[2022-12-06T22:07:04.078+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-06T22:07:04.096+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
