[2022-12-06T22:05:07.291+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-06T22:05:01.766855+00:00 [queued]>
[2022-12-06T22:05:07.343+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-06T22:05:01.766855+00:00 [queued]>
[2022-12-06T22:05:07.345+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T22:05:07.347+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-06T22:05:07.348+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T22:05:07.419+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): pull_data> on 2022-12-06 22:05:01.766855+00:00
[2022-12-06T22:05:07.440+0000] {standard_task_runner.py:55} INFO - Started process 1734 to run task
[2022-12-06T22:05:07.458+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'pull_data', 'manual__2022-12-06T22:05:01.766855+00:00', '--job-id', '1179', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpbm4w31d1']
[2022-12-06T22:05:07.461+0000] {standard_task_runner.py:83} INFO - Job 1179: Subtask pull_data
[2022-12-06T22:05:07.710+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.pull_data manual__2022-12-06T22:05:01.766855+00:00 [running]> on host 505aa50095aa
[2022-12-06T22:05:07.865+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T22:05:01.766855+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T22:05:01.766855+00:00
[2022-12-06T22:05:07.883+0000] {logging_mixin.py:137} INFO - connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2022-12-06T22:05:07.884+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-06T22:05:07.906+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=pull_data, execution_date=20221206T220501, start_date=20221206T220507, end_date=20221206T220507
[2022-12-06T22:05:07.982+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-06T22:05:08.021+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
