[2022-12-07T09:29:35.878+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T09:29:29.765533+00:00 [queued]>
[2022-12-07T09:29:35.896+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T09:29:29.765533+00:00 [queued]>
[2022-12-07T09:29:35.897+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T09:29:35.897+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T09:29:35.898+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T09:29:35.917+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): pull_data> on 2022-12-07 09:29:29.765533+00:00
[2022-12-07T09:29:35.923+0000] {standard_task_runner.py:55} INFO - Started process 1790 to run task
[2022-12-07T09:29:35.928+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'pull_data', 'manual__2022-12-07T09:29:29.765533+00:00', '--job-id', '1610', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpeq5t3ihi']
[2022-12-07T09:29:35.929+0000] {standard_task_runner.py:83} INFO - Job 1610: Subtask pull_data
[2022-12-07T09:29:35.999+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.pull_data manual__2022-12-07T09:29:29.765533+00:00 [running]> on host 505aa50095aa
[2022-12-07T09:29:36.078+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T09:29:29.765533+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T09:29:29.765533+00:00
[2022-12-07T09:29:36.099+0000] {logging_mixin.py:137} INFO - Postgresql connection created!
[2022-12-07T09:29:36.102+0000] {logging_mixin.py:137} INFO - duplicate key value violates unique constraint "pairs_pkey"
DETAIL:  Key (date, ticker_from, ticker_to)=(2022-12-07 00:00:00, USD, EUR) already exists.
[2022-12-07T09:29:36.103+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-07T09:29:36.117+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=pull_data, execution_date=20221207T092929, start_date=20221207T092935, end_date=20221207T092936
[2022-12-07T09:29:36.141+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-07T09:29:36.159+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
